### PR TITLE
Enable ImageMagick conversion

### PR DESCRIPTION
**Pull request by mserranom**
Setting was added in https://github.com/overleaf/filestore/pull/43

### CODE REVIEW

**Review by das7pad — CHANGES_REQUESTED** [review]
The filestore is part of the OSS version. Maybe move the new setting out of the Server Pro section?

**Comment by mserranom** [comment]
@das7pad You have a point. However conversion feature is not used in Community edition, and Server Pro block in settings is to highlight attention of Pro users, in case they want to disable it due to security concerns, so I think I prefer to keep it there.

**Comment by das7pad** [comment]
What do you think about adding a comment referring to the mentioned filestore Issue?

**Comment by mserranom** [comment]
I'm closing this CR in favour of https://github.com/overleaf/docker-image/pull/115.

This one was created from the wrong branch, polluting the diffs.

**Pull request closed without merging**
