### PR TITLE
Make the image build faster and more efficient

### PR DESCRIPTION
**Pull request by bcdonadio**
This set of patches minimizes the number of layers, increasing the build speed, and also removes nginx. Ideally, nginx should be run in a different container, with docker-compose. I will post the docker-compose.yml I am using ASAP.

### CODE REVIEW

**Comment by bcdonadio** [comment]
Ooops. Found a bug. Please don't merge it yet.

**Comment by bcdonadio** [comment]
Ok. Now everything should be working.

Also, I've put the docker-compose configs, with nginx, redis and mongo in different containers (with the default public images).

**Comment by bcdonadio** [comment]
The pull request was rebased to the latest changes.

**Comment by henryoswald** [comment]
Thanks, I have taken a lot of these points and used them rather than merging the PR.

**Pull request closed without merging**
